input.onButtonPressed(Button.A, function () {
    basic.showString("Yes")
    basic.clearScreen()
})
input.onButtonPressed(Button.B, function () {
    basic.showString("No")
    basic.clearScreen()
})
basic.pause(10)
basic.showString("Do you like fruits")
basic.pause(100)
basic.forever(function () {
    basic.showString("Do you like apple")
    basic.pause(5000)
    basic.showString("Do you like banana")
    basic.pause(5000)
    basic.showString("Do you like grapefruit")
    basic.pause(5000)
    basic.showString("Do you like apricot")
    basic.pause(5000)
    basic.showString("Do you like blueberry")
    basic.pause(5000)
    basic.showString("Do you like cherry")
    basic.pause(5000)
    basic.showString("Do you like fig")
    basic.pause(5000)
    basic.showString("Do you like grape")
    basic.pause(5000)
    basic.showString("Do you like kiwi")
    basic.pause(5000)
    basic.showString("Do you like lemon")
    basic.pause(5000)
    basic.showString("Do you like peach")
    basic.pause(5000)
    basic.showString("Do you like pear")
    basic.pause(5000)
    basic.showString("Do you like strawbery")
    basic.pause(5000)
    basic.showString("Do you like pineapple")
    basic.pause(5000)
    basic.showString("Do you like watermelon")
    basic.pause(5000)
    basic.clearScreen()
})
